-- MySQL Script generated by MySQL Workbench
-- 05/17/15 21:29:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workflow
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `workflow` ;

-- -----------------------------------------------------
-- Schema workflow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workflow` DEFAULT CHARACTER SET latin1 ;
USE `workflow` ;

-- -----------------------------------------------------
-- Table `authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authorities` ;

CREATE TABLE IF NOT EXISTS `authorities` (
  `Username` VARCHAR(60) NOT NULL,
  `Authority` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

CREATE TABLE IF NOT EXISTS `customer` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(1000) NOT NULL,
  `Admin` TINYINT(1) NOT NULL,
  `Enabled` TINYINT(1) NOT NULL,
  `HasFacebook` TINYINT(1) NOT NULL,
  `HasInstagram` TINYINT(1) NOT NULL,
  `HasTwitter` TINYINT(1) NOT NULL,
  `HasGoogle` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `logging`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logging` ;

CREATE TABLE IF NOT EXISTS `logging` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TextPosted` VARCHAR(500) NULL,
  `PicturePosted` TINYINT(1) NULL,
  `PostedAt` DATETIME NOT NULL,
  `State` ENUM('Pending','Sucessful','Unsucessful') NOT NULL,
  `MediaName` ENUM('Facebook','Twitter','Instagram','Google') NOT NULL,
  `Customer_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_logging_customer1_idx` (`Customer_Id` ASC),
  CONSTRAINT `fk_logging_customer1`
    FOREIGN KEY (`Customer_Id`)
    REFERENCES `customer` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_media_channels_parameters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_media_channels_parameters` ;

CREATE TABLE IF NOT EXISTS `user_media_channels_parameters` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FacebookToken` VARCHAR(45) NULL,
  `Customer_Id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_user_media_channels_parameters_customer_idx` (`Customer_Id` ASC),
  CONSTRAINT `fk_user_media_channels_parameters_customer`
    FOREIGN KEY (`Customer_Id`)
    REFERENCES `customer` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
