-- MySQL Script generated by MySQL Workbench
-- 05/09/15 11:49:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema andatu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS 'andatu' ;

-- -----------------------------------------------------
-- Schema andatu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS 'andatu' DEFAULT CHARACTER SET latin1 ;
USE 'andatu' ;

-- -----------------------------------------------------
-- Table 'authorities'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'authorities' ;

CREATE TABLE IF NOT EXISTS 'authorities' (
  'Username' VARCHAR(60) NOT NULL,
  'Authority' VARCHAR(60) NOT NULL,
  PRIMARY KEY ('Username'))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'categories'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'categories' ;

CREATE TABLE IF NOT EXISTS 'categories' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY ('Id'))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'state'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'state' ;

CREATE TABLE IF NOT EXISTS 'state' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY ('Id'))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'city'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'city' ;

CREATE TABLE IF NOT EXISTS 'city' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Name' VARCHAR(70) NOT NULL,
  'STATE_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_CITY_STATE1_idx' ('STATE_FK' ASC),
  CONSTRAINT 'fk_CITY_STATE1'
    FOREIGN KEY ('STATE_FK')
    REFERENCES 'state' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'customer'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'customer' ;

CREATE TABLE IF NOT EXISTS 'customer' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'FirstName' VARCHAR(45) NOT NULL,
  'LastName' VARCHAR(45) NOT NULL,
  'Title' VARCHAR(45) NOT NULL,
  'DOB' DATETIME NOT NULL,
  'Email' VARCHAR(45) NOT NULL,
  'Password' VARCHAR(1000) NOT NULL,
  'Language' VARCHAR(45) NOT NULL,
  'PictureLink' VARCHAR(45) NULL DEFAULT NULL,
  'Admin' TINYINT(1) NOT NULL,
  'HonorPoints' INT(11) NULL DEFAULT NULL,
  'Phone' VARCHAR(45) NULL DEFAULT NULL,
  'NewsLetter' TINYINT(1) NOT NULL,
  'enabled' BIT(1) NOT NULL,
  PRIMARY KEY ('Id'),
  UNIQUE INDEX 'Email_UNIQUE' ('Email' ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'product'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'product' ;

CREATE TABLE IF NOT EXISTS 'product' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Name' VARCHAR(45) NOT NULL,
  'Description' VARCHAR(1000) NOT NULL,
  'HashTags' VARCHAR(1000) NOT NULL,
  'Price' DOUBLE(6,2) NOT NULL,
  'PurchasePrice' DOUBLE(6,2) NULL DEFAULT NULL,
  'Availability' TINYINT(1) NOT NULL,
  'productCondition' VARCHAR(45) NOT NULL,
  'CUSTOMER_FK' INT(11) NOT NULL,
  'CATEGORIES_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_PRODUCT_CUSTOMER1_idx' ('CUSTOMER_FK' ASC),
  INDEX 'fk_PRODUCT_CATEGORIES1_idx' ('CATEGORIES_FK' ASC),
  CONSTRAINT 'fk_PRODUCT_CATEGORIES1'
    FOREIGN KEY ('CATEGORIES_FK')
    REFERENCES 'categories' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_PRODUCT_CUSTOMER1'
    FOREIGN KEY ('CUSTOMER_FK')
    REFERENCES 'customer' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'comment'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'comment' ;

CREATE TABLE IF NOT EXISTS 'comment' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Comment' VARCHAR(1000) NOT NULL,
  'Private' TINYINT(1) NOT NULL,
  'PRODUCT_FK' INT(11) NOT NULL,
  'COMMENT_FK' INT(11) NULL DEFAULT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_COMMENT_PRODUCT1_idx' ('PRODUCT_FK' ASC),
  INDEX 'fk_COMMENT_COMMENT1_idx' ('COMMENT_FK' ASC),
  CONSTRAINT 'fk_COMMENT_COMMENT1'
    FOREIGN KEY ('COMMENT_FK')
    REFERENCES 'comment' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_COMMENT_PRODUCT1'
    FOREIGN KEY ('PRODUCT_FK')
    REFERENCES 'product' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'customer_address'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'customer_address' ;

CREATE TABLE IF NOT EXISTS 'customer_address' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Address' VARCHAR(70) NOT NULL,
  'Address2' VARCHAR(70) NULL DEFAULT NULL,
  'ZIP_CODE' VARCHAR(11) NOT NULL,
  'CUSTOMER_FK' INT(11) NOT NULL,
  'CITY_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_CUSTOMER_ADDRESS_CUSTOMER1_idx' ('CUSTOMER_FK' ASC),
  INDEX 'fk_CUSTOMER_ADDRESS_CITY1_idx' ('CITY_FK' ASC),
  CONSTRAINT 'fk_CUSTOMER_ADDRESS_CITY1'
    FOREIGN KEY ('CITY_FK')
    REFERENCES 'city' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_CUSTOMER_ADDRESS_CUSTOMER1'
    FOREIGN KEY ('CUSTOMER_FK')
    REFERENCES 'customer' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'customer_bank_account'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'customer_bank_account' ;

CREATE TABLE IF NOT EXISTS 'customer_bank_account' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Name' VARCHAR(45) NOT NULL,
  'IBAN' VARCHAR(45) NOT NULL,
  'BIC' VARCHAR(45) NOT NULL,
  'CUSTOMER_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_CUSTOMER_ACCOUNT_CUSTOMER1_idx' ('CUSTOMER_FK' ASC),
  CONSTRAINT 'fk_CUSTOMER_ACCOUNT_CUSTOMER1'
    FOREIGN KEY ('CUSTOMER_FK')
    REFERENCES 'customer' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'delivery_destination'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'delivery_destination' ;

CREATE TABLE IF NOT EXISTS 'delivery_destination' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY ('Id'))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'delivery_method'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'delivery_method' ;

CREATE TABLE IF NOT EXISTS 'delivery_method' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'DELIVERY_DESTINATION_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_delivery_method_delivery_destination1_idx' ('DELIVERY_DESTINATION_FK' ASC),
  CONSTRAINT 'fk_delivery_method_delivery_destination1'
    FOREIGN KEY ('DELIVERY_DESTINATION_FK')
    REFERENCES 'delivery_destination' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'ngo'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'ngo' ;

CREATE TABLE IF NOT EXISTS 'ngo' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Name' VARCHAR(75) NOT NULL,
  'IDNumber' VARCHAR(45) NOT NULL,
  'Email' VARCHAR(45) NOT NULL,
  'Password' VARCHAR(45) NOT NULL,
  'Language' VARCHAR(45) NOT NULL,
  'Description' VARCHAR(4000) NOT NULL,
  'Phone' VARCHAR(45) NULL DEFAULT NULL,
  'WebsiteLink' VARCHAR(90) NULL DEFAULT NULL,
  'Confirmed' TINYINT(1) NOT NULL,
  PRIMARY KEY ('Id'))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'donation'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'donation' ;

CREATE TABLE IF NOT EXISTS 'donation' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Percentage' SMALLINT(3) NOT NULL,
  'PRODUCT_FK' INT(11) NOT NULL,
  'NGO_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_DONATION_PRODUCT1_idx' ('PRODUCT_FK' ASC),
  INDEX 'fk_DONATION_NGO1_idx' ('NGO_FK' ASC),
  CONSTRAINT 'fk_DONATION_NGO1'
    FOREIGN KEY ('NGO_FK')
    REFERENCES 'ngo' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_DONATION_PRODUCT1'
    FOREIGN KEY ('PRODUCT_FK')
    REFERENCES 'product' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'ngo_address'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'ngo_address' ;

CREATE TABLE IF NOT EXISTS 'ngo_address' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Address' VARCHAR(70) NOT NULL,
  'Address2' VARCHAR(70) NULL DEFAULT NULL,
  'ZIP_CODE' VARCHAR(11) NOT NULL,
  'NGO_FK' INT(11) NOT NULL,
  'CITY_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_CUSTOMER_ADDRESS_CITY1_idx' ('CITY_FK' ASC),
  INDEX 'fk_NGO_ADDRESS_NGO1_idx' ('NGO_FK' ASC),
  CONSTRAINT 'fk_CUSTOMER_ADDRESS_CITY10'
    FOREIGN KEY ('CITY_FK')
    REFERENCES 'city' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_NGO_ADDRESS_NGO1'
    FOREIGN KEY ('NGO_FK')
    REFERENCES 'ngo' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'ngo_bank_account'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'ngo_bank_account' ;

CREATE TABLE IF NOT EXISTS 'ngo_bank_account' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Name' VARCHAR(45) NOT NULL,
  'IBAN' VARCHAR(45) NOT NULL,
  'BIC' VARCHAR(45) NOT NULL,
  'NGO_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_NGO_ACCOUNT_NGO1_idx' ('NGO_FK' ASC),
  CONSTRAINT 'fk_NGO_ACCOUNT_NGO1'
    FOREIGN KEY ('NGO_FK')
    REFERENCES 'ngo' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'ngo_pictures'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'ngo_pictures' ;

CREATE TABLE IF NOT EXISTS 'ngo_pictures' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Link' VARCHAR(45) NOT NULL,
  'NGO_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_NGO_PICTURES_NGO_idx' ('NGO_FK' ASC),
  CONSTRAINT 'fk_NGO_PICTURES_NGO'
    FOREIGN KEY ('NGO_FK')
    REFERENCES 'ngo' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'product_pictures'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'product_pictures' ;

CREATE TABLE IF NOT EXISTS 'product_pictures' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Name' VARCHAR(45) NOT NULL,
  'Description' VARCHAR(45) NULL DEFAULT NULL,
  'Location' VARCHAR(255) NOT NULL,
  'Size' INT(20) NOT NULL,
  'Type' VARCHAR(45) NOT NULL,
  'PRODUCT_FK' INT(11) NULL DEFAULT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_PRODUCT_PICTURES_PRODUCT1_idx' ('PRODUCT_FK' ASC),
  CONSTRAINT 'fk_PRODUCT_PICTURES_PRODUCT1'
    FOREIGN KEY ('PRODUCT_FK')
    REFERENCES 'product' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'product_delivery_method'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'product_delivery_method' ;

CREATE TABLE IF NOT EXISTS 'product_delivery_method' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Price' DOUBLE(7,2) NOT NULL,
  'DELIVERY_METHOD_FK' INT(11) NOT NULL,
  'PRODUCT_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_delivery_method_delivery_method1_idx' ('DELIVERY_METHOD_FK' ASC),
  INDEX 'fk_delivery_method_product1_idx' ('PRODUCT_FK' ASC),
  CONSTRAINT 'fk_delivery_method_delivery_method1'
    FOREIGN KEY ('DELIVERY_METHOD_FK')
    REFERENCES 'delivery_method' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_delivery_method_product1'
    FOREIGN KEY ('PRODUCT_FK')
    REFERENCES 'product' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'transaction'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'transaction' ;

CREATE TABLE IF NOT EXISTS 'transaction' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'Status' VARCHAR(45) NOT NULL,
  'PurchaseDate' DATETIME NULL DEFAULT NULL,
  'PayedDate' DATETIME NULL DEFAULT NULL,
  'SentDate' DATETIME NULL DEFAULT NULL,
  'RecivedDate' DATETIME NULL DEFAULT NULL,
  'NGOTransferDate' DATETIME NULL DEFAULT NULL,
  'PaymentMethod' VARCHAR(45) NOT NULL,
  'CUSTOMER_FK' INT(11) NOT NULL,
  'PRODUCT_FK' INT(11) NOT NULL,
  'PRODUCT_DELIVERY_METHOD_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_TRANSACTION_CUSTOMER1_idx' ('CUSTOMER_FK' ASC),
  INDEX 'fk_TRANSACTION_PRODUCT1_idx' ('PRODUCT_FK' ASC),
  INDEX 'fk_transaction_product_delivery_method1_idx' ('PRODUCT_DELIVERY_METHOD_FK' ASC),
  CONSTRAINT 'fk_TRANSACTION_CUSTOMER1'
    FOREIGN KEY ('CUSTOMER_FK')
    REFERENCES 'customer' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_TRANSACTION_PRODUCT1'
    FOREIGN KEY ('PRODUCT_FK')
    REFERENCES 'product' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_transaction_product_delivery_method1'
    FOREIGN KEY ('PRODUCT_DELIVERY_METHOD_FK')
    REFERENCES 'product_delivery_method' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'wishlist'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'wishlist' ;

CREATE TABLE IF NOT EXISTS 'wishlist' (
  'Id' INT(11) NOT NULL AUTO_INCREMENT,
  'CUSTOMER_FK' INT(11) NOT NULL,
  'PRODUCT_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_WISHLIST_CUSTOMER1_idx' ('CUSTOMER_FK' ASC),
  INDEX 'fk_WISHLIST_PRODUCT1_idx' ('PRODUCT_FK' ASC),
  CONSTRAINT 'fk_WISHLIST_CUSTOMER1'
    FOREIGN KEY ('CUSTOMER_FK')
    REFERENCES 'customer' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_WISHLIST_PRODUCT1'
    FOREIGN KEY ('PRODUCT_FK')
    REFERENCES 'product' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table 'state_translation'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'state_translation' ;

CREATE TABLE IF NOT EXISTS 'state_translation' (
  'Id' INT(11) NOT NULL,
  'Name' VARCHAR(70) NOT NULL,
  'Language' VARCHAR(2) NOT NULL,
  'IsDefault' TINYINT(1) NOT NULL,
  'STATE_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_state_translations_state1_idx' ('STATE_FK' ASC),
  CONSTRAINT 'fk_state_translations_state1'
    FOREIGN KEY ('STATE_FK')
    REFERENCES 'state' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'categories_translation'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'categories_translation' ;

CREATE TABLE IF NOT EXISTS 'categories_translation' (
  'Id' INT(11) NOT NULL,
  'Name' VARCHAR(70) NOT NULL,
  'Language' VARCHAR(2) NOT NULL,
  'IsDefault' TINYINT(1) NOT NULL,
  'CATEGORIES_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_state_translations_categories1_idx' ('CATEGORIES_FK' ASC),
  CONSTRAINT 'fk_state_translations_categories1'
    FOREIGN KEY ('CATEGORIES_FK')
    REFERENCES 'categories' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'delivery_method_translation'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'delivery_method_translation' ;

CREATE TABLE IF NOT EXISTS 'delivery_method_translation' (
  'Id' INT(11) NOT NULL,
  'Name' VARCHAR(70) NOT NULL,
  'Language' VARCHAR(2) NOT NULL,
  'IsDefault' TINYINT(1) NOT NULL,
  'DELIVERY_METHOD_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_state_translations_delivery_method1_idx' ('DELIVERY_METHOD_FK' ASC),
  CONSTRAINT 'fk_state_translations_delivery_method1'
    FOREIGN KEY ('DELIVERY_METHOD_FK')
    REFERENCES 'delivery_method' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'delivery_destination_translation'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'delivery_destination_translation' ;

CREATE TABLE IF NOT EXISTS 'delivery_destination_translation' (
  'Id' INT(11) NOT NULL,
  'Name' VARCHAR(70) NOT NULL,
  'Language' VARCHAR(2) NOT NULL,
  'IsDefault' TINYINT(1) NOT NULL,
  'DELIVERY_DESTINATION_FK' INT(11) NOT NULL,
  PRIMARY KEY ('Id'),
  INDEX 'fk_state_translations_delivery_destination1_idx' ('DELIVERY_DESTINATION_FK' ASC),
  CONSTRAINT 'fk_state_translations_delivery_destination1'
    FOREIGN KEY ('DELIVERY_DESTINATION_FK')
    REFERENCES 'delivery_destination' ('Id')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
